source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.3"

gem "rails", "~> 7.0.8"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# job
gem "sidekiq"

# auth
gem "bcrypt", "~> 3.1.7"
gem 'jwt'

# view
gem 'kaminari'

# upload
gem 'carrierwave'
gem 'rmagick'
gem 'fog', require: 'fog/aws'
gem 'fog-aws'
gem 'mini_magick'

# graphql
gem 'rack-cors'
gem 'graphql'
gem 'graphql_apollo_upload_client_params', git: 'https://github.com/github0013/graphql_apollo_upload_client_params.git'

# config
gem 'enum_help'

# db
gem 'seed-fu'
gem 'acts_as_list'

# aws
gem 'aws-sdk'
gem 'aws-sdk-rails'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem 'annotate'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-nav'
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"

end
gem "graphiql-rails", group: :development
